# Generated by Django 5.1 on 2024-08-16 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0003_mascota_cliente_alter_mascota_especie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cita',
            name='confirmada',
        ),
        migrations.AddField(
            model_name='cita',
            name='area',
            field=models.CharField(default='Consulta', max_length=100),
        ),
        migrations.AddField(
            model_name='cita',
            name='especialidad',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='cita',
            name='hora_seleccionada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.cliente'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.veterinario'),
        ),
    ]
