# Generated by Django 5.1 on 2024-08-17 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0005_remove_cita_mascota_alter_cita_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='mascota',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mi_app.mascota'),
        ),
    ]
