# Generated by Django 5.1 on 2024-08-18 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0006_cita_mascota'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.mascota')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.medicoveterinario')),
            ],
        ),
    ]
