# Generated by Django 5.1 on 2024-08-18 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0007_registromedico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='cliente',
        ),
        migrations.AlterField(
            model_name='mascota',
            name='peso',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nota', models.TextField()),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='mi_app.mascota')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.medicoveterinario')),
            ],
        ),
    ]
