# Generated by Django 5.1 on 2024-08-18 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0009_alter_cita_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'permissions': [('can_view_own_data', 'Can view own data'), ('can_add_pet', 'Can add pet'), ('can_view_pet', 'Can view pet'), ('can_edit_pet', 'Can edit pet'), ('can_delete_pet', 'Can delete pet'), ('can_request_appointment', 'Can request appointment'), ('can_manage_appointments', 'Can manage appointments'), ('can_view_appointments', 'Can view appointments'), ('can_view_chat', 'Can view chat'), ('can_manage_chat', 'Can manage chat')]},
        ),
    ]
